Repository 5iobook/ubookstore, pull requests merged in 2025-06, with the labels that each got.

#4 pr template 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📄 docs, ⚙ setting

#5 ⚙ setting [#3-post] post 서비스 생성
  .gradle/8.10/fileHashes/fileHashes.bin
  .gradle/8.10/fileHashes/fileHashes.lock
  .idea/compiler.xml
  .idea/gradle.xml
  post/.gitattributes
  post/.gitignore
  post/build.gradle
  post/gradle/wrapper/gradle-wrapper.jar
  post/gradle/wrapper/gradle-wrapper.properties
  post/gradlew
  post/gradlew.bat
  post/settings.gradle
  post/src/main/java/com/bookstore/post/PostApplication.java
  post/src/main/resources/application.properties
  post/src/test/java/com/bookstore/post/PostApplicationTests.java
  settings.gradle
Labels: ⚙ setting

#7 ⚙ setting [#6-post] 초기 설정
  .gradle/8.10/checksums/checksums.lock
  .gradle/8.10/checksums/md5-checksums.bin
  .gradle/8.10/checksums/sha1-checksums.bin
  .gradle/8.10/fileHashes/fileHashes.lock
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/modules.xml
  .idea/modules/post.main.iml
  .idea/modules/post/bookstore.post.main.iml
  post/build.gradle
Labels: ⚙ setting

#9 ✨ feat [#8-post] 게시글 CRUD Controller, DTO 생성
  .gitignore
  .gradle/8.10/checksums/checksums.lock
  .gradle/8.10/checksums/md5-checksums.bin
  .gradle/8.10/checksums/sha1-checksums.bin
  .gradle/8.10/dependencies-accessors/gc.properties
  .gradle/8.10/executionHistory/executionHistory.bin
  .gradle/8.10/executionHistory/executionHistory.lock
  .gradle/8.10/fileChanges/last-build.bin
  .gradle/8.10/fileHashes/fileHashes.bin
  .gradle/8.10/fileHashes/fileHashes.lock
  .gradle/8.10/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  .gradle/vcs-1/gc.properties
  post/src/main/java/com/bookstore/post/common/application/dto/ResDTO.java
  post/src/main/java/com/bookstore/post/post/application/dto/v1/request/ReqPostPostDTOApiV1.java
  post/src/main/java/com/bookstore/post/post/application/dto/v1/request/ReqPostPutDTOApiV1.java
  post/src/main/java/com/bookstore/post/post/application/dto/v1/response/ResPostGetByIdDTOApiV1.java
  post/src/main/java/com/bookstore/post/post/application/dto/v1/response/ResPostGetDTOApiV1.java
  post/src/main/java/com/bookstore/post/post/application/dto/v1/response/ResPostPostDTOApiV1.java
  post/src/main/java/com/bookstore/post/post/application/dto/v1/response/ResPostPutDTOApiV1.java
  post/src/main/java/com/bookstore/post/post/domain/entity/PostEntity.java
  post/src/main/java/com/bookstore/post/post/domain/entity/Price.java
  post/src/main/java/com/bookstore/post/post/domain/vo/PostStatus.java
  post/src/main/java/com/bookstore/post/post/domain/vo/ProductCondition.java
  post/src/main/java/com/bookstore/post/post/presentation/controller/v1/PostControllerApiV1.java
  post/src/main/resources/application-dev.yml
  post/src/main/resources/application.properties
  post/src/main/resources/application.yml
  post/src/test/java/com/bookstore/post/httpClient/post.http
Labels: ✨ feat

#11 ✨ feat [#10-hashtag] 해시태그 CRUD Controller, DTO 생성
  post/src/main/java/com/bookstore/post/hashtag/application/dto/v1/request/ReqHashtagPostDTOApiV1.java
  post/src/main/java/com/bookstore/post/hashtag/application/dto/v1/request/ReqHashtagPutDTOApiV1.java
  post/src/main/java/com/bookstore/post/hashtag/application/dto/v1/response/ResHashtagGetByIdDTOApiV1.java
  post/src/main/java/com/bookstore/post/hashtag/application/dto/v1/response/ResHashtagGetDTOApiV1.java
  post/src/main/java/com/bookstore/post/hashtag/application/dto/v1/response/ResHashtagPostDTOApiV1.java
  post/src/main/java/com/bookstore/post/hashtag/application/dto/v1/response/ResHashtagPutDTOApiV1.java
  post/src/main/java/com/bookstore/post/hashtag/domain/entity/HashtagEntity.java
  post/src/main/java/com/bookstore/post/hashtag/presentation/controller/v1/HashtagControllerApiV1.java
  post/src/test/java/com/bookstore/post/httpClient/hashtag.http
Labels: ✨ feat

#18 ✨Feat [#17-trade] 거래 Api 구현
  docker-compose.yml
  settings.gradle
  trade/build.gradle
  trade/src/main/java/com/bookstore/trade/TradeApplication.java
  trade/src/main/java/com/bookstore/trade/application/dto/v1/request/ReqTradeCancelDtoApiV1.java
  trade/src/main/java/com/bookstore/trade/application/dto/v1/request/ReqTradeRequestDtoApiV1.java
  trade/src/main/java/com/bookstore/trade/application/dto/v1/response/ResTradeAcceptDtoApiV1.java
  trade/src/main/java/com/bookstore/trade/application/dto/v1/response/ResTradeCancelDtoApiV1.java
  trade/src/main/java/com/bookstore/trade/application/dto/v1/response/ResTradeCompleteDtoApiV1.java
  trade/src/main/java/com/bookstore/trade/application/dto/v1/response/ResTradeGetDetailListDtoApiV1.java
  trade/src/main/java/com/bookstore/trade/application/dto/v1/response/ResTradeRequestDtoApiV1.java
  trade/src/main/java/com/bookstore/trade/application/service/v1/TradeServiceApiV1.java
  trade/src/main/java/com/bookstore/trade/application/service/v1/TradeServiceApiV1Impl.java
  trade/src/main/java/com/bookstore/trade/domain/trade/entity/TradeEntity.java
  trade/src/main/java/com/bookstore/trade/domain/trade/repository/TradeRepository.java
  trade/src/main/java/com/bookstore/trade/domain/trade/vo/TradeMethod.java
  trade/src/main/java/com/bookstore/trade/domain/trade/vo/TradeStatus.java
  trade/src/main/java/com/bookstore/trade/presentation/controller/v1/TradeControllerApiV1.java
  trade/src/main/resources/application.yml
  trade/src/test/java/http/Trade.http
Labels: ✨ feat

#32 ⚙ setting [#31-wish] 위시 서비스 모듈 생성
  settings.gradle
  wish/.gitattributes
  wish/.gitignore
  wish/build.gradle
  wish/gradle/wrapper/gradle-wrapper.jar
  wish/gradle/wrapper/gradle-wrapper.properties
  wish/gradlew
  wish/gradlew.bat
  wish/src/main/java/com/bookstore/wish/WishApplication.java
  wish/src/main/resources/application-dev.yml
  wish/src/main/resources/application.yml
  wish/src/test/java/com/bookstore/wish/WishApplicationTests.java
Labels: ⚙ setting

#34 ⚙ setting [#33-eureka] 유레카 서버 생성
  eureka-server/.gitattributes
  eureka-server/.gitignore
  eureka-server/build.gradle
  eureka-server/gradle/wrapper/gradle-wrapper.jar
  eureka-server/gradle/wrapper/gradle-wrapper.properties
  eureka-server/gradlew
  eureka-server/gradlew.bat
  eureka-server/src/main/java/com/bookstore/eurekaserver/EurekaServerApplication.java
  eureka-server/src/main/resources/application.yml
  eureka-server/src/test/java/com/bookstore/eurekaserver/EurekaServerApplicationTests.java
  settings.gradle
Labels: ⚙ setting

#40 ⚙ setting [#39 eureka] .gitignore 설정 변경 및 Eureka 스프링 버전 변경
  .gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/modules.xml
  .idea/modules/user/bookstore.user.main.iml
  eureka-server/build.gradle
Labels: ⚙ setting

#42 ⚙ setting [#41-post] 유레카 연결 및 스프링 버전 변경
  post/build.gradle
  post/src/main/resources/application-dev.yml
Labels: ⚙ setting

#44 ✨ feat [#43-wish] 찜 생성 구현
  wish/build.gradle
  wish/src/main/java/com/bookstore/wish/WishApplication.java
  wish/src/main/java/com/bookstore/wish/application/dto/v1/response/ResWishPostDTOApiV1.java
  wish/src/main/java/com/bookstore/wish/application/exception/WishExceptionCode.java
  wish/src/main/java/com/bookstore/wish/application/service/v1/WishServiceApiV1.java
  wish/src/main/java/com/bookstore/wish/application/service/v1/WishServiceImplApiV1.java
  wish/src/main/java/com/bookstore/wish/domain/entity/WishEntity.java
  wish/src/main/java/com/bookstore/wish/domain/repository/WishRepository.java
  wish/src/main/java/com/bookstore/wish/infrastructure/client/PostFeignClientApiV1.java
  wish/src/main/java/com/bookstore/wish/infrastructure/client/dto/ResPostGetByIdDTOApiV1.java
  wish/src/main/java/com/bookstore/wish/infrastructure/persistence/WishJpaRepository.java
  wish/src/main/java/com/bookstore/wish/presentation/controller/v1/WishControllerApiV1.java
  wish/src/main/resources/application-dev.yml
  wish/src/test/java/com/bookstore/wish/httpClient/wish.http
Labels: ⚙ setting, ✨ feat

#48 ✨ feat [#47-post-wish] 게시글 존재 여부를 확인하는 API 추가
  post/src/main/java/com/bookstore/post/post/application/service/v1/PostServiceApiV1.java
  post/src/main/java/com/bookstore/post/post/application/service/v1/PostServiceImplApiV1.java
  post/src/main/java/com/bookstore/post/post/presentation/controller/v1/PostControllerApiV1.java
  wish/src/main/java/com/bookstore/wish/application/service/v1/WishServiceImplApiV1.java
  wish/src/main/java/com/bookstore/wish/infrastructure/client/PostFeignClientApiV1.java
  wish/src/main/java/com/bookstore/wish/infrastructure/client/dto/ResPostGetByIdDTOApiV1.java
Labels: 🔨 refactor, ✨ feat

#50 ✨ feat [#49 wish] 본인 찜 목록 조회 및 찜 취소 구현
  wish/src/main/java/com/bookstore/wish/application/dto/v1/response/ResWishGetDTOApiV1.java
  wish/src/main/java/com/bookstore/wish/application/exception/WishExceptionCode.java
  wish/src/main/java/com/bookstore/wish/application/service/v1/WishServiceApiV1.java
  wish/src/main/java/com/bookstore/wish/application/service/v1/WishServiceImplApiV1.java
  wish/src/main/java/com/bookstore/wish/domain/entity/WishEntity.java
  wish/src/main/java/com/bookstore/wish/domain/repository/WishRepository.java
  wish/src/main/java/com/bookstore/wish/presentation/controller/v1/WishControllerApiV1.java
  wish/src/test/java/com/bookstore/wish/httpClient/wish.http
Labels: ✨ feat

#53 ✨ feat [#52-post-wish] 게시글 찜 수 증감 기능 구현
  post/src/main/java/com/bookstore/post/post/application/service/v1/PostServiceApiV1.java
  post/src/main/java/com/bookstore/post/post/application/service/v1/PostServiceImplApiV1.java
  post/src/main/java/com/bookstore/post/post/domain/entity/PostEntity.java
  post/src/main/java/com/bookstore/post/post/presentation/controller/v1/InternalPostController.java
  post/src/main/java/com/bookstore/post/post/presentation/controller/v1/PostControllerApiV1.java
  wish/src/main/java/com/bookstore/wish/application/service/v1/WishServiceImplApiV1.java
  wish/src/main/java/com/bookstore/wish/infrastructure/client/PostFeignClientApiV1.java
Labels: ✨ feat

#46 ✨feat [#45-trade] common 연동 및 검색 API 추가
  trade/build.gradle
  trade/src/main/java/com/bookstore/trade/application/dto/v1/response/ResTradeGetSearchListDtoApiV1.java
  trade/src/main/java/com/bookstore/trade/application/service/v1/TradeServiceApiV1.java
  trade/src/main/java/com/bookstore/trade/application/service/v1/TradeServiceApiV1Impl.java
  trade/src/main/java/com/bookstore/trade/domain/trade/entity/TradeEntity.java
  trade/src/main/java/com/bookstore/trade/domain/trade/repository/TradeRepository.java
  trade/src/main/java/com/bookstore/trade/infrastructure/exception/TradeExceptionCode.java
  trade/src/main/java/com/bookstore/trade/infrastructure/persistence/TradeJpaRepository.java
  trade/src/main/java/com/bookstore/trade/presentation/controller/v1/TradeControllerApiV1.java
  trade/src/main/resources/application.yml
  trade/src/test/java/http/Trade.http
Labels: 🔨 refactor, ✨ feat
